user:
    path:     /
    defaults: { _controller: "CdlrUserBundle:User:index" }

user_show:
    path:     /{id}/show
    defaults: { _controller: "CdlrUserBundle:User:show" }

user_new:
    path:     /new
    defaults: { _controller: "CdlrUserBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "CdlrUserBundle:User:create" }
    methods:  POST
    
gerant_user_create:
    path:     /gerant_create
    defaults: { _controller: "CdlrUserBundle:AdminSide:gerantcreate" }
    methods:  GET
    
admin_user_create:
    path:     /admin_create
    defaults: { _controller: "CdlrUserBundle:AdminSide:admincreate" }
    methods:  GET

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "CdlrUserBundle:User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "CdlrUserBundle:User:update" }
    methods:  [POST, PUT]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "CdlrUserBundle:User:delete" }
    methods:  [POST, DELETE]
