cdlr_user_user:
    resource: "@CdlrUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

admin_homepage:
    path:     /admin
    defaults: { _controller: CdlrcodeBundle:Default:admin }
    
liste_admin:
    path:     /admin/liste_admin
    defaults: { _controller: CdlrUserBundle:User:admin }
    
liste_candidat:
    path:     /admin/liste_candidat
    defaults: { _controller: CdlrUserBundle:User:candidat }

liste_gerant:
    path:     /admin/liste_gerant
    defaults: { _controller: CdlrUserBundle:User:gerant }

liste_moniteur:
    path:     /admin/liste_moniteur
    defaults: { _controller: CdlrUserBundle:User:moniteur }
    
gerant_homepage:
    path:     /home/gerant
    defaults: { _controller: CdlrcodeBundle:Default:gerant }
    
moniteur_homepage:
    path:     /home/moniteur
    defaults: { _controller: CdlrcodeBundle:Default:moniteur }

cdlr_user_homepage:
    path:     /home
    defaults: { _controller: CdlrUserBundle:Default:index }
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /login

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
_security_check_facebook:
    pattern:   /facebook/login_check
    defaults:  { _controller: CdlrUserBundle:User:loginFb }

_security_facebook_logout:
  pattern:  /facebook/logout

user_couple_fb_with_account:
    pattern: /user/couple/facebook
    defaults: { _controller: CdlrUserBundle:User:connectFacebookWithAccount }
    
#fos_user_register_admin:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register/user
